{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "milvus-cluster.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "milvus-cluster.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{- include "milvus-cluster.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
  {{- $annotations := merge (dict) (.Values.serviceAccount.annotations | default dict) }}
  {{- $common := include "milvus-cluster.annotations" . }}
  {{- if or $annotations (trim $common) }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- include "milvus-cluster.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
    {{- with .Values.extraAnnotations }}
    {{- include "milvus-cluster.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end -}}
