apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.headlessServiceName" . }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: true
  ports:
    {{- include "helm.servicePorts" . | nindent 4 }}