apiVersion: v2
name: etcd
description: A Helm chart for ETCD
type: application
version: 0.1.0
appVersion: "v3.7.0"
icon: https://raw.githubusercontent.com/eurodyn/ed-helm-charts/main/logo_ed.png
maintainers:
  - name: European Dynamics SA
    url: https://www.eurodyn.com
    email: info@eurodyn.com
